### ISSUE TITLE
EQ-P invokes implementation-defined behavior

### ISSUE THREAD

**Issue by phoe** [noloop/assert-p#1]
```common-lisp
(eq-p 1 3) => throw assertion-error
```

It is implementation-defined whether comparing two numbers by EQ returns `T` or `NIL`, therefore this check may or may not signal an `ASSERTION-ERROR`.

**Comment by noloop** [comment]
This is true, I was inattentive, I mainly use the SBCL where `(eq 3 3)` I have always been the equals, but in the case:

`(eq-p 1 3) => throw assertion-error`

Yes, throw an `assertion-error`, `(eq 3 3)` may be T or NIL, but `(eq 1 3) ` will always be NIL.

_At least I imagine that, but I do not know for sure._

**Comment by phoe** [comment]
Yes, that is correct, `(eq 1 3)` should always return `NIL`. I am mostly mentioning this for correctness, since numbers should not be compared with `eq` - it's a soft type error.

**Comment by noloop** [comment]
True, I'll delete this line of documentation as soon as I get home.

**Comment by phoe** [comment]
No need to delete it - just use a better-defined `=` instead of `eq`.

**Comment by noloop** [comment]
could create another `=-p`, but do not change `eq-p` to use `=`, since the goal is to have an accessible `eq`.

**Comment by noloop** [comment]
I preferred to add a comment: https://github.com/noloop/assert-p/commit/0e78490f0b57567a867c7ce5b28477a5921e6436
